### ISSUE TITLE
能否新增預覽功能？

### ISSUE THREAD

**Issue by zhtw2013** [zhyipeng/yank-note-extension-snippet#3]
感謝 zhyipeng 大神開發的套件
讓 YN 更方便使用了

在這裡想提個建議
能否在 輸入 /關鍵字 時
可以預覽該關鍵字的內容呢？

感謝！

**Comment by zhyipeng** [comment]
感谢支持, 目前已有解决方案, 不过需要 yn 支持, 已向 yn 提 pr, 等待下版本更新
