### ISSUE TITLE
功能增强

### ISSUE THREAD

**Issue by StarLeet** [zhyipeng/yank-note-extension-snippet#4]
请问可以实现光标定位悬停吗?
比如我这样: 
`<img src="$1" alt="$2" width="$3" height="$4">`
片段插入后,光标先停在$1,tab依次向右悬停
感谢作者付出

**Comment by purocean** [comment]
https://github.com/zhyipeng/yank-note-extension-snippet/assets/7115690/3f4f6c5b-ad47-4b81-8308-1e5941271424

看样子是支持的
